### ISSUE TITLE
crash when trying to compile i32x4 type with upstream llvm

### ISSUE THREAD

**Issue by lenawanel** [sx-aurora-dev/llvm-project#247]
as mentioned in llvm/llvm-project/issues/64420 trying to compile SIMD types with upstream llvm causes crashes. 
it works fine with the llvm from this repo however.

Me and @freemin7 are working porting rust to the Vector Engine, and this problem is a big blocker for us. 

We would like to know if there are plans to upstream the changes required to compile i32x4 type.

**Comment by kaz7** [comment]
This problem is solved in the upstream.
