### ISSUE TITLE
need to merge fc8d376

### ISSUE THREAD

**Issue by jam7** [sx-aurora-dev/llvm-project#42]
@simoll -san, can you merge fc8d376?

It causes ExtVectorBoolType related conflicts.  I could not merge it correctly at first try.  I've merged up to 265bc5a which is just one previous of fc8d376.  Thanks!

**Comment by simoll** [comment]
I've merged that commit on the https://github.com/sx-aurora-dev/llvm-project/tree/feature/merge-ext-vector-select branch.

**Comment by jam7** [comment]
Thank you! I'll run regression tests and nightly tests.  I'll merge your branch once it passes tests.

**Comment by kaz7** [comment]
I've merged this at #43.  Thanks!
