### ISSUE TITLE
Need to merge 2813acb

### ISSUE THREAD

**Issue by kaz7** [sx-aurora-dev/llvm-project#51]
@simoll -san, can you merge 2813acb?  Merging this causes compile error.

Previously, we modify llvm/include/llvm/IR/PatternMatch to use not only match but also match_context.  However, this patch adds undef_match newly.  We again need to modify this undef_match to work with match_context well.

I've merged up to dd68942 which is one predecessor of 2813acb.

**Comment by simoll** [comment]
Alright. Fixed in ff3058e

**Comment by kaz7** [comment]
Merged by #53.
