### ISSUE TITLE
Need to apply b159987

### ISSUE THREAD

**Issue by kaz7** [sx-aurora-dev/llvm-project#55]
Need to apply b159987.  This patch in upstream supports only integer VP instructions.  Hoever, VE has floating-point VP instructions, so need to improve b159987.

@simoll -san, can you apply it for me?  Thanks.

**Comment by simoll** [comment]
Merged on https://github.com/sx-aurora-dev/llvm-project/tree/merge/vp-unittest-cleanup

**Comment by kaz7** [comment]
Thanks!

**Comment by kaz7** [comment]
Merged by #57.
