### ISSUE TITLE
Missing architecture detection for ve in openmp build

### ISSUE THREAD

**Issue by Sekuraz** [sx-aurora-dev/llvm-project#7]
In the following line there should be a detection for sx-aurora architecture in order to bring the openmp build in line with the builds for other architectures. https://github.com/sx-aurora-dev/llvm-project/blob/eed12a1f8f9f398c5712424bbbee8d1fd338023b/openmp/runtime/cmake/LibompGetArchitecture.cmake#L50

**Comment by kaz7** [comment]
Thank you.  I changed it locally in 524adca45abb2a28c539d4894aed33794b54b996.  I'll upstream it soon.

**Comment by kaz7** [comment]
We upstreamed this.

https://github.com/sx-aurora-dev/llvm-project/blob/18b67243550a4f2ef12cc2d93a12f5bfecb50752/openmp/runtime/cmake/LibompGetArchitecture.cmake#L52-L54
